/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/integrations/audio/jobs/{job_id}/transcription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a completed transcription from the audio-to-text service */
        post: operations["receive_transcription_api_v1_integrations_audio_jobs__job_id__transcription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/text/jobs/{job_id}/mom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a completed draft MoM from the text service */
        post: operations["receive_mom_api_v1_integrations_text_jobs__job_id__mom_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist an audio upload and queue a pipeline job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read persisted pipeline job status */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/mom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the persisted draft MoM JSON */
        get: operations["get_mom_api_v1_jobs__job_id__mom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger mock retry */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/review-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read compact metadata for the review-ready portal view */
        get: operations["get_review_context_api_v1_jobs__job_id__review_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the persisted structured transcription result */
        get: operations["get_transcript_api_v1_jobs__job_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger mock liveness read */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger mock readiness read */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactAvailability */
        ArtifactAvailability: {
            /** Momavailable */
            momAvailable: boolean;
            /** Reviewcontextavailable */
            reviewContextAvailable: boolean;
            /** Transcriptavailable */
            transcriptAvailable: boolean;
        };
        /** ArtifactLink */
        ArtifactLink: {
            /** Available */
            available: boolean;
            /** Href */
            href: string;
        };
        /** AudioMetadata */
        AudioMetadata: {
            /** Durationms */
            durationMs: number;
        };
        /** Body_create_job_api_v1_jobs_post */
        Body_create_job_api_v1_jobs_post: {
            /**
             * Audio
             * @description Audio recording, up to 300 MiB
             */
            audio: string;
        };
        /** CreateJobResponse */
        CreateJobResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Jobid */
            jobId: string;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
        };
        /** DetectedLanguage */
        DetectedLanguage: {
            /** Code */
            code: string;
            /** Proportion */
            proportion: number;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "QUEUED" | "TRANSCRIBING" | "GENERATING_MOM" | "AWAITING_REVIEW" | "FAILED";
        /** JobStatusResponse */
        JobStatusResponse: {
            artifacts: components["schemas"]["ArtifactAvailability"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            error: components["schemas"]["JobError"] | null;
            /** Jobid */
            jobId: string;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** LanguageDetection */
        LanguageDetection: {
            /** Languages */
            languages: components["schemas"]["DetectedLanguage"][];
        };
        /** MeetingMetadata */
        MeetingMetadata: {
            /** Durationms */
            durationMs: number;
            /** Languages */
            languages: components["schemas"]["DetectedLanguage"][];
            /** Namedspeakercount */
            namedSpeakerCount: number;
            /** Speakercount */
            speakerCount: number;
        };
        /** MomQuality */
        MomQuality: {
            /**
             * Confidencescale
             * @constant
             */
            confidenceScale: "ZERO_TO_ONE";
            /** Momconfidence */
            momConfidence: number;
        };
        /** MomReceipt */
        MomReceipt: {
            /** Jobid */
            jobId: string;
            /** Replayed */
            replayed: boolean;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
        };
        /** MomResult */
        MomResult: {
            /** Document */
            document: {
                [key: string]: unknown;
            };
            quality: components["schemas"]["MomQuality"];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "mom.v1alpha1";
        };
        /** ProcessingSummary */
        ProcessingSummary: {
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
            /** Elapsedms */
            elapsedMs: number;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
        };
        /** PublicSubmittedBy */
        PublicSubmittedBy: {
            /** Displayname */
            displayName?: string | null;
            /** Userid */
            userId: string;
        };
        /** ReviewArtifactLinks */
        ReviewArtifactLinks: {
            mom: components["schemas"]["ArtifactLink"];
            transcript: components["schemas"]["ArtifactLink"];
        };
        /**
         * ReviewContextResponse
         * @description Browser-facing context with the submitter email intentionally omitted.
         */
        ReviewContextResponse: {
            artifacts: components["schemas"]["ReviewArtifactLinks"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Jobid */
            jobId: string;
            meetingMetadata: components["schemas"]["MeetingMetadata"];
            processing: components["schemas"]["ProcessingSummary"];
            quality: components["schemas"]["ReviewQuality"];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "review-context.v1alpha1";
            sourceRecording: components["schemas"]["ReviewSourceRecording"];
            /** Speakers */
            speakers: components["schemas"]["TranscriptionSpeaker"][];
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
            submittedBy: components["schemas"]["PublicSubmittedBy"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ReviewQuality */
        ReviewQuality: {
            /**
             * Confidencescale
             * @constant
             */
            confidenceScale: "ZERO_TO_ONE";
            /** Momconfidence */
            momConfidence: number;
            /** Overallconfidence */
            overallConfidence: number | null;
            /** Transcriptconfidence */
            transcriptConfidence: number;
        };
        /** ReviewSourceRecording */
        ReviewSourceRecording: {
            /** Durationms */
            durationMs: number;
            /** Mediatype */
            mediaType: string;
            /** Originalfilename */
            originalFileName: string;
            /** Sizebytes */
            sizeBytes: number;
        };
        /** TranscriptContent */
        TranscriptContent: {
            /** Segments */
            segments: components["schemas"]["TranscriptSegment"][];
            /** Text */
            text: string;
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Confidence */
            confidence: number | null;
            /** Endms */
            endMs: number | null;
            /** Id */
            id: string;
            /** Languages */
            languages: string[];
            /** Speakerid */
            speakerId: string | null;
            /** Startms */
            startMs: number;
            /** Text */
            text: string;
        };
        /** TranscriptionQuality */
        TranscriptionQuality: {
            /**
             * Confidencescale
             * @constant
             */
            confidenceScale: "ZERO_TO_ONE";
            /** Transcriptconfidence */
            transcriptConfidence: number;
        };
        /** TranscriptionReceipt */
        TranscriptionReceipt: {
            /** Jobid */
            jobId: string;
            /** Replayed */
            replayed: boolean;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
        };
        /** TranscriptionResult */
        TranscriptionResult: {
            audioMetadata: components["schemas"]["AudioMetadata"];
            /** Jobid */
            jobId: string;
            languageDetection: components["schemas"]["LanguageDetection"];
            quality: components["schemas"]["TranscriptionQuality"];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: "transcription.v1alpha1";
            /** Speakers */
            speakers: components["schemas"]["TranscriptionSpeaker"][];
            transcript: components["schemas"]["TranscriptContent"];
        };
        /** TranscriptionSpeaker */
        TranscriptionSpeaker: {
            /** Displayname */
            displayName: string | null;
            /** Id */
            id: string;
            /** Languages */
            languages: string[];
            /** Speakingtimeproportion */
            speakingTimeProportion: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    receive_transcription_api_v1_integrations_audio_jobs__job_id__transcription_post: {
        parameters: {
            query?: never;
            header: {
                "X-Audio-Model-Job-Id": string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptionResult"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionReceipt"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionReceipt"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    receive_mom_api_v1_integrations_text_jobs__job_id__mom_post: {
        parameters: {
            query?: never;
            header: {
                "X-Text-Model-Job-Id": string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MomResult"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomReceipt"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomReceipt"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_api_v1_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_mom_api_v1_jobs__job_id__mom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_context_api_v1_jobs__job_id__review_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewContextResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_transcript_api_v1_jobs__job_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
