/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the local demo staff directory */
        get: operations["get_directory_api_v1_directory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/audio/jobs/{job_id}/transcription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a completed transcription from the audio-to-text service */
        post: operations["receive_transcription_api_v1_integrations_audio_jobs__job_id__transcription_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integrations/text/jobs/{job_id}/mom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist a completed draft MoM from the text service */
        post: operations["receive_mom_api_v1_integrations_text_jobs__job_id__mom_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Persist an audio upload and queue a pipeline job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read persisted pipeline job status */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve a MoM and optionally deliver it through local SMTP */
        post: operations["approve_mom_api_v1_jobs__job_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/approved-mom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the persisted approved MoM */
        get: operations["get_approved_mom_api_v1_jobs__job_id__approved_mom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/mom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the persisted draft MoM JSON */
        get: operations["get_mom_api_v1_jobs__job_id__mom_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Persist reviewer-confirmed names for diarized speakers */
        put: operations["save_participant_assignments_api_v1_jobs__job_id__participants_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger mock retry */
        post: operations["retry_job_api_v1_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/review-context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read compact metadata for the review-ready portal view */
        get: operations["get_review_context_api_v1_jobs__job_id__review_context_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read the persisted structured transcription result */
        get: operations["get_transcript_api_v1_jobs__job_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger mock liveness read */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trigger mock readiness read */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalRequest */
        ApprovalRequest: {
            document: components["schemas"]["MomDocument"];
            /** Recipients */
            recipients: string[];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** ApprovedMom */
        ApprovedMom: {
            /**
             * Approvedat
             * Format: date-time
             */
            approvedAt: string;
            document: components["schemas"]["MomDocument"];
            /** Jobid */
            jobId: string;
            /** Recipients */
            recipients: string[];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            /** Skippedrecipients */
            skippedRecipients: string[];
        };
        /** ArtifactAvailability */
        ArtifactAvailability: {
            /** Momavailable */
            momAvailable: boolean;
            /** Reviewcontextavailable */
            reviewContextAvailable: boolean;
            /** Transcriptavailable */
            transcriptAvailable: boolean;
        };
        /** ArtifactLink */
        ArtifactLink: {
            /** Available */
            available: boolean;
            /** Href */
            href: string;
        };
        /** AudioMetadata */
        AudioMetadata: {
            /** Durationms */
            durationMs: number;
            /** Recordedat */
            recordedAt?: string | null;
        };
        /** Body_create_job_api_v1_jobs_post */
        Body_create_job_api_v1_jobs_post: {
            /**
             * Audio
             * @description Audio recording, up to 300 MiB
             */
            audio: string;
        };
        /** CreateJobResponse */
        CreateJobResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Jobid */
            jobId: string;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
        };
        /** DetectedLanguage */
        DetectedLanguage: {
            /** Code */
            code: string;
            /** Proportion */
            proportion: number;
        };
        /**
         * DirectoryPerson
         * @description One locally maintained person available to portal autocomplete.
         */
        DirectoryPerson: {
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Title */
            title?: string | null;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobError */
        JobError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "QUEUED" | "TRANSCRIBING" | "GENERATING_MOM" | "AWAITING_REVIEW" | "COMPLETED" | "FAILED";
        /** JobStatusResponse */
        JobStatusResponse: {
            artifacts: components["schemas"]["ArtifactAvailability"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            error: components["schemas"]["JobError"] | null;
            /** Jobid */
            jobId: string;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** LanguageDetection */
        LanguageDetection: {
            /** Languages */
            languages: components["schemas"]["DetectedLanguage"][];
        };
        /** MeetingMetadata */
        MeetingMetadata: {
            /** Durationms */
            durationMs: number;
            /** Languages */
            languages: components["schemas"]["DetectedLanguage"][];
            /** Namedspeakercount */
            namedSpeakerCount: number;
            /** Speakercount */
            speakerCount: number;
        };
        /** MomAction */
        MomAction: {
            deadline: components["schemas"]["MomDeadline"];
            /** Decision Ids */
            decision_ids?: string[] | null;
            evidence: components["schemas"]["MomEvidence"];
            /** Flags */
            flags: components["schemas"]["MomFlag"][];
            /** Id */
            id: string;
            /** Owner */
            owner?: string | null;
            /** Text */
            text: string;
        };
        /** MomDeadline */
        MomDeadline: {
            /** Resolved */
            resolved?: string | null;
            /** Spoken */
            spoken?: string | null;
        };
        /** MomDecision */
        MomDecision: {
            evidence: components["schemas"]["MomEvidence"];
            /** Flags */
            flags: components["schemas"]["MomFlag"][];
            /** Id */
            id: string;
            /** Revised In Meeting */
            revised_in_meeting?: boolean | null;
            /**
             * Status
             * @enum {string}
             */
            status: "decided" | "proposed" | "revoked";
            /** Text */
            text: string;
        };
        /**
         * MomDocument
         * @description The validated schema-version-1 review document consumed by the portal.
         */
        MomDocument: {
            /** Actions */
            actions: components["schemas"]["MomAction"][];
            /** Decisions */
            decisions: components["schemas"]["MomDecision"][];
            /** Findings */
            findings: components["schemas"]["MomFinding"][];
            header: components["schemas"]["MomHeader"];
            /** Open Questions */
            open_questions: components["schemas"]["MomOpenQuestion"][];
            /** Patients */
            patients?: components["schemas"]["MomPatient"][] | null;
            /** Risks */
            risks: components["schemas"]["MomRisk"][];
            /** Summary */
            summary: string;
            /** Topics */
            topics: components["schemas"]["MomTopic"][];
        };
        /**
         * MomEvidence
         * @description Trace an MoM statement to an immutable transcription segment ID.
         */
        MomEvidence: {
            /**
             * Lang
             * @enum {string}
             */
            lang: "ro" | "ru" | "en" | "mixed";
            /** Quote */
            quote: string;
            /** Segment */
            segment?: number | null;
            /** Segment Id */
            segment_id: string;
            /** Speaker */
            speaker?: string | null;
            /** T */
            t?: string | null;
        };
        /** MomFinding */
        MomFinding: {
            evidence: components["schemas"]["MomEvidence"];
            /** Flags */
            flags: components["schemas"]["MomFlag"][];
            /** Source Stated */
            source_stated?: string | null;
            /** Text */
            text: string;
        };
        /** MomFlag */
        MomFlag: {
            /** Blocking */
            blocking: boolean;
            /** Candidates */
            candidates?: string[] | null;
            /** Reason */
            reason: string;
            /**
             * Type
             * @enum {string}
             */
            type: "number" | "decision_status" | "owner" | "deadline" | "term";
        };
        /** MomHeader */
        MomHeader: {
            /** Also Discussed */
            also_discussed?: ("medical" | "patient_case" | "financial" | "administrative" | "executive" | "operational" | "crisis" | "other")[] | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Date Source
             * @enum {string}
             */
            date_source: "recording" | "upload";
            /** Duration Min */
            duration_min?: number | null;
            /** Languages */
            languages?: {
                [key: string]: number;
            } | null;
            /**
             * Meeting Type
             * @enum {string}
             */
            meeting_type: "medical" | "patient_case" | "financial" | "administrative" | "executive" | "operational" | "crisis" | "other";
            /**
             * Meeting Type Confidence
             * @enum {string}
             */
            meeting_type_confidence: "high" | "medium" | "low";
            /** Participants Mentioned */
            participants_mentioned?: components["schemas"]["MomParticipant"][] | null;
            /** Subject */
            subject: string;
        };
        /** MomOpenQuestion */
        MomOpenQuestion: {
            evidence?: components["schemas"]["MomEvidence"] | null;
            /** Raised By */
            raised_by?: string | null;
            /** Text */
            text: string;
        };
        /** MomParticipant */
        MomParticipant: {
            /** Name */
            name: string;
            /** Role */
            role?: string | null;
            /** Role Stated */
            role_stated?: boolean | null;
        };
        /** MomPatient */
        MomPatient: {
            /** Decision Ids */
            decision_ids: string[];
            /** Findings */
            findings?: string[] | null;
            /** Plan */
            plan?: string | null;
            /** Reference */
            reference: string;
        };
        /** MomQuality */
        MomQuality: {
            /**
             * Confidencescale
             * @constant
             */
            confidenceScale: "ZERO_TO_ONE";
            /** Momconfidence */
            momConfidence?: number | null;
        };
        /** MomReceipt */
        MomReceipt: {
            /** Jobid */
            jobId: string;
            /** Replayed */
            replayed: boolean;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
        };
        /** MomResult */
        MomResult: {
            document: components["schemas"]["MomDocument"];
            quality: components["schemas"]["MomQuality"];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** MomRisk */
        MomRisk: {
            /** Category */
            category?: ("clinical" | "safety" | "technical" | "regulatory" | "data_quality" | "operational") | null;
            evidence?: components["schemas"]["MomEvidence"] | null;
            /** Raised By */
            raised_by?: string | null;
            /** Text */
            text: string;
        };
        /** MomTopic */
        MomTopic: {
            /** Text */
            text: string;
            /** Title */
            title: string;
        };
        /**
         * ParticipantAssignment
         * @description A reviewer-confirmed display name for one diarized speaker.
         */
        ParticipantAssignment: {
            /** Displayname */
            displayName: string;
            /** Speakerid */
            speakerId: string;
        };
        /** ParticipantAssignments */
        ParticipantAssignments: {
            /** Assignments */
            assignments: components["schemas"]["ParticipantAssignment"][];
            /** Jobid */
            jobId: string;
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ParticipantAssignmentsRequest */
        ParticipantAssignmentsRequest: {
            /** Assignments */
            assignments: components["schemas"]["ParticipantAssignment"][];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
        };
        /** ProcessingSummary */
        ProcessingSummary: {
            /** Audiostagems */
            audioStageMs?: number | null;
            /**
             * Completedat
             * Format: date-time
             */
            completedAt: string;
            /** Elapsedms */
            elapsedMs: number;
            /** Momstagems */
            momStageMs?: number | null;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
        };
        /** PublicSubmittedBy */
        PublicSubmittedBy: {
            /** Displayname */
            displayName?: string | null;
            /** Userid */
            userId: string;
        };
        /** ReviewArtifactLinks */
        ReviewArtifactLinks: {
            mom: components["schemas"]["ArtifactLink"];
            transcript: components["schemas"]["ArtifactLink"];
        };
        /**
         * ReviewContextResponse
         * @description Browser-facing context with the submitter email intentionally omitted.
         */
        ReviewContextResponse: {
            artifacts: components["schemas"]["ReviewArtifactLinks"];
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Jobid */
            jobId: string;
            meetingMetadata: components["schemas"]["MeetingMetadata"];
            processing: components["schemas"]["ProcessingSummary"];
            quality: components["schemas"]["ReviewQuality"];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            sourceRecording: components["schemas"]["ReviewSourceRecording"];
            /** Speakers */
            speakers: components["schemas"]["TranscriptionSpeaker"][];
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
            submittedBy: components["schemas"]["PublicSubmittedBy"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ReviewQuality */
        ReviewQuality: {
            /**
             * Confidencescale
             * @constant
             */
            confidenceScale: "ZERO_TO_ONE";
            /** Momconfidence */
            momConfidence?: number | null;
            /** Overallconfidence */
            overallConfidence: number | null;
            /** Transcriptconfidence */
            transcriptConfidence?: number | null;
        };
        /** ReviewSourceRecording */
        ReviewSourceRecording: {
            /** Durationms */
            durationMs: number;
            /** Mediatype */
            mediaType: string;
            /** Originalfilename */
            originalFileName: string;
            /** Recordedat */
            recordedAt?: string | null;
            /** Sizebytes */
            sizeBytes: number;
        };
        /** TranscriptContent */
        TranscriptContent: {
            /** Segments */
            segments: components["schemas"]["TranscriptSegment"][];
            /** Text */
            text: string;
        };
        /** TranscriptSegment */
        TranscriptSegment: {
            /** Confidence */
            confidence: number | null;
            /** Endms */
            endMs: number | null;
            /** Id */
            id: string;
            /** Languages */
            languages: string[];
            /** Speakerid */
            speakerId: string | null;
            /** Startms */
            startMs: number;
            /** Text */
            text: string;
        };
        /** TranscriptionQuality */
        TranscriptionQuality: {
            /**
             * Confidencescale
             * @constant
             */
            confidenceScale: "ZERO_TO_ONE";
            /** Transcriptconfidence */
            transcriptConfidence?: number | null;
        };
        /** TranscriptionReceipt */
        TranscriptionReceipt: {
            /** Jobid */
            jobId: string;
            /** Replayed */
            replayed: boolean;
            /** Stage */
            stage: string;
            status: components["schemas"]["JobStatus"];
        };
        /** TranscriptionResult */
        TranscriptionResult: {
            audioMetadata: components["schemas"]["AudioMetadata"];
            /** Jobid */
            jobId: string;
            languageDetection: components["schemas"]["LanguageDetection"];
            quality: components["schemas"]["TranscriptionQuality"];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            /** Speakers */
            speakers: components["schemas"]["TranscriptionSpeaker"][];
            transcript: components["schemas"]["TranscriptContent"];
        };
        /** TranscriptionSpeaker */
        TranscriptionSpeaker: {
            /** Displayname */
            displayName: string | null;
            /** Id */
            id: string;
            /** Languages */
            languages: string[];
            /** Speakingtimeproportion */
            speakingTimeProportion: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_directory_api_v1_directory_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectoryPerson"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receive_transcription_api_v1_integrations_audio_jobs__job_id__transcription_post: {
        parameters: {
            query?: never;
            header: {
                "X-Audio-Model-Job-Id": string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptionResult"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionReceipt"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionReceipt"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    receive_mom_api_v1_integrations_text_jobs__job_id__mom_post: {
        parameters: {
            query?: never;
            header: {
                "X-Text-Model-Job-Id": string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MomResult"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomReceipt"];
                };
            };
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomReceipt"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_job_api_v1_jobs_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateJobResponse"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Request Entity Too Large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unsupported Media Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    approve_mom_api_v1_jobs__job_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovedMom"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Bad Gateway */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_approved_mom_api_v1_jobs__job_id__approved_mom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovedMom"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_mom_api_v1_jobs__job_id__mom_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MomResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    save_participant_assignments_api_v1_jobs__job_id__participants_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantAssignmentsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantAssignments"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    retry_job_api_v1_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_context_api_v1_jobs__job_id__review_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewContextResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_transcript_api_v1_jobs__job_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResult"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
